# Generated by Django 5.1.5 on 2025-03-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_taskdetail_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdetail",
            name="asset",
            field=models.ImageField(blank=True, null=True, upload_to="tasks_asset"),
        ),
    ]
