# Generated by Django 5.1.5 on 2025-03-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_taskdetail_asset"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskdetail",
            old_name="asset",
            new_name="assets",
        ),
    ]
