# Generated by Django 5.1.5 on 2025-03-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_rename_asset_taskdetail_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdetail",
            name="assets",
            field=models.ImageField(
                blank=True,
                default="tasks_asset/default_img.jpg",
                null=True,
                upload_to="tasks_asset",
            ),
        ),
    ]
